In [ ]:
lst = [1,2,3,4,5]

In [ ]:
import numpy
numpy.array(lst)

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np
np.array(lst)

array([1, 2, 3, 4, 5])

In [ ]:
type(np.array(lst))

numpy.ndarray

In [ ]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]
type(lst1)

list

In [ ]:
np.array(lst1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#2d array
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#eye matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5) #5X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [ ]:
np.arange(0,5) #a-range

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [ ]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.arange(20,45,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44])

In [ ]:
#linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.linspace(-10,-5,3)

array([-10. ,  -7.5,  -5. ])

In [ ]:
np.linspace(0,10,100)

In [ ]:
#generate random numbers between (0,1)
np.random.rand(5)

array([0.84495691, 0.22444002, 0.61325997, 0.0699583 , 0.04970444])

In [ ]:
#generate random numbers between ant two integer
np.random.randint(1,10)  #10 exclusive

1

In [ ]:
np.random.randint(1,100,100)

array([77, 78, 26, 98, 69, 56,  1, 72,  9, 15, 55, 15, 36, 36, 41, 20, 85,
       57, 19, 43, 14, 17, 79, 14, 53,  1, 28,  7, 11, 28, 45, 60, 25, 55,
       57, 35,  9, 40, 86, 58, 24, 84, 74, 61,  6, 23, 57, 23, 23, 43, 75,
       14, 62, 95, 25, 14, 31, 80, 86, 49, 28, 83, 81, 62, 47, 17, 90, 11,
       30, 80, 14, 93, 75, 12, 16, 81, 56, 46, 70, 60,  4,  4, 43,  6, 52,
       58, 67, 81, 14, 57, 57, 60, 45, 55,  2, 38, 34, 30, 64, 59])

In [ ]:
narr = np.arange(0,15)
narr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
narr.shape

(15,)

In [ ]:
narr.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [ ]:
narr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
narr1 = np.random.randint(0,100,10)

In [ ]:
narr1

array([36, 56, 69, 42, 38, 90, 92, 95, 41, 70])

In [ ]:
narr1.min()

36

In [ ]:
narr1.max()

95

In [ ]:
narr1.argmax()

7

In [ ]:
narr1.argmin()

0

In [ ]:
narr1[7]

95

In [ ]:
narr1[0]

36

In [ ]:
narr1.dtype

dtype('int64')

In [ ]:
narr2 = np.random.rand(10)
narr2

array([0.89195178, 0.47025646, 0.11399629, 0.97586748, 0.02493558,
       0.21856023, 0.65899588, 0.69225636, 0.94700742, 0.00777067])

In [ ]:
narr2.dtype

dtype('float64')

In [ ]:
narr3 = np.ones(6)

In [ ]:
print(narr3)
print(narr3.dtype)
print(type(narr3))

[1. 1. 1. 1. 1. 1.]
float64
<class 'numpy.ndarray'>


In [ ]:
narr3.astype(int)   #changing type inside the array

array([1, 1, 1, 1, 1, 1])

In [ ]:
nlist = np.random.randint(-5,10,3)
print(nlist)
print(nlist.dtype)

[ 0  3 -5]
int64


In [ ]:
narray = np.arange(0,20)
narray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
narray.shape   #note (20,)= 1X20

(20,)

In [ ]:
print(narray.reshape(20,1))
print(narray.reshape(20,1).shape)
print(narray.reshape(4,5))
print(narray.reshape(10,2))
print(narray.reshape(5,4))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
(20, 1)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
narray.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
narray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
print(narray[0])   #print by calling from index
print(narray[5])

0
5


In [ ]:
narray[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
narray[0:2]   # 2 exclusive

array([0, 1])

In [ ]:
narray[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
narray[0:15:3]

array([ 0,  3,  6,  9, 12])

In [ ]:
narray[4::]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
narray[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
narray[18:3:-3]

array([18, 15, 12,  9,  6])

In [ ]:
narray[-1]

19

In [ ]:
narray[-3]

17

In [ ]:
narray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
nlst = np.random.randint(0,40,15)

In [ ]:
nlst

array([ 3, 19, 11, 25, 14, 14, 11, 19, 15, 30,  2, 26,  0, 21, 29])

In [ ]:
nlst*5

array([ 15,  95,  55, 125,  70,  70,  55,  95,  75, 150,  10, 130,   0,
       105, 145])

In [ ]:
nlst[:5]*5

array([ 15,  95,  55, 125,  70])

In [ ]:
#broadcasting
nlst[0:5] = 100
nlst

array([100, 100, 100, 100, 100,  14,  11,  19,  15,  30,   2,  26,   0,
        21,  29])

In [ ]:
nlst1 = np.random.randint(0,10,5)

In [ ]:
nlst1

array([8, 1, 4, 8, 8])

In [ ]:
print(nlst1*5)
print(nlst1/5)
print(nlst1 + nlst1)


[40  5 20 40 40]
[1.6 0.2 0.8 1.6 1.6]
[16  2  8 16 16]


In [ ]:
print(nlst * nlst)

[10000 10000 10000 10000 10000   196   121   361   225   900     4   676
     0   441   841]


In [ ]:
print(nlst/nlst)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. nan  1.  1.]


<ipython-input-57-3849db898424>:1: RuntimeWarning: invalid value encountered in true_divide
  print(nlst/nlst)


In [ ]:
narr_2d = np.arange(1,10).reshape(3,3)

In [ ]:
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
narr_2d[0]

array([1, 2, 3])

In [ ]:
narr_2d[0:3]  # 3 exclusive

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
narr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
narr_2d[0][0]

1

In [ ]:
narr_2d[1][1]

5

In [ ]:
narr_2d[1][1:3]

array([5, 6])

In [ ]:
narray_2d = np.random.randint(1,100,36).reshape(6,6)

In [ ]:
narray_2d

array([[58, 98, 42,  1, 22, 89],
       [70, 52,  4, 21, 96, 68],
       [12, 48, 49, 22, 14, 20],
       [97, 43, 45, 37, 59, 30],
       [ 6, 50, 55, 58, 45,  7],
       [ 7, 11, 50, 74, 14, 54]])

In [ ]:
narray_2d[0:2]

array([[58, 98, 42,  1, 22, 89],
       [70, 52,  4, 21, 96, 68]])

In [ ]:
narray_2d[::-1]

array([[ 7, 11, 50, 74, 14, 54],
       [ 6, 50, 55, 58, 45,  7],
       [97, 43, 45, 37, 59, 30],
       [12, 48, 49, 22, 14, 20],
       [70, 52,  4, 21, 96, 68],
       [58, 98, 42,  1, 22, 89]])

In [ ]:
narray_2d[:3,3:]

array([[ 1, 22, 89],
       [21, 96, 68],
       [22, 14, 20]])

In [ ]:
narray_2d[2:,2:]

array([[49, 22, 14, 20],
       [45, 37, 59, 30],
       [55, 58, 45,  7],
       [50, 74, 14, 54]])

In [ ]:
narray_2d[2:4,3:4]

array([[22],
       [37]])

In [ ]:
narray_2d[1:4, 1:5]

array([[52,  4, 21, 96],
       [48, 49, 22, 14],
       [43, 45, 37, 59]])

In [ ]:
narray1 = np.random.randint(1,100,15)

In [ ]:
narray1

array([57, 79, 22, 26, 88, 80, 99, 24, 99, 19, 80, 29, 97, 70, 12])

In [ ]:
narray1[narray1 > 50]

array([57, 79, 88, 80, 99, 99, 80, 97, 70])

In [ ]:
np.sqrt(narray1)

array([7.54983444, 8.88819442, 4.69041576, 5.09901951, 9.38083152,
       8.94427191, 9.94987437, 4.89897949, 9.94987437, 4.35889894,
       8.94427191, 5.38516481, 9.8488578 , 8.36660027, 3.46410162])

In [ ]:
print(np.sin(narray1))
print(np.cos(narray1))

[ 0.43616476 -0.44411267 -0.00885131  0.76255845  0.0353983  -0.99388865
 -0.99920683 -0.90557836 -0.99920683  0.14987721 -0.99388865 -0.66363388
  0.37960774  0.77389068 -0.53657292]
[ 0.89986683 -0.89597095 -0.99996083  0.64691932  0.99937328 -0.11038724
  0.03982088  0.42417901  0.03982088  0.98870462 -0.11038724 -0.74805753
 -0.92514754  0.6333192   0.84385396]


In [ ]:
np.log(narray1)

array([4.04305127, 4.36944785, 3.09104245, 3.25809654, 4.47733681,
       4.38202663, 4.59511985, 3.17805383, 4.59511985, 2.94443898,
       4.38202663, 3.36729583, 4.57471098, 4.24849524, 2.48490665])